# -*- mode: ruby -*-
# vi: set ft=ruby :
# export VAGRANT_EXPERIMENTAL="disks"

Vagrant.configure("2") do |config|

  config.vm.box = 'centos/8.4'
  config.vm.box_url = 'https://cloud.centos.org/centos/8/x86_64/images/CentOS-8-Vagrant-8.4.2105-20210603.0.x86_64.vagrant-virtualbox.box'
  config.vm.box_download_checksum = 'dfe4a34e59eb3056a6fe67625454c3607cbc52ae941aeba0498c29ee7cb9ac22'
  config.vm.box_download_checksum_type = 'sha256'

config.vm.define "server" do |server|

  server.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  server.vm.disk :disk, size: "1GB", name: "disk1"
  server.vm.disk :disk, size: "1GB", name: "disk2"
  server.vm.disk :disk, size: "1GB", name: "disk3"
  server.vm.host_name = 'server'
  server.vm.network :private_network, ip: "10.0.0.41"



  server.vm.provision "shell", inline: <<-SHELL
		cd /etc/yum.repos.d/
		sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
		sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
		touch /etc/profile.d/histtimeformat.sh
		echo "export HISTTIMEFORMAT='[ %d/%m/%y %T ]'">> /etc/profile.d/histtimeformat.sh
		yum install -y mc wget time lsof
		bash /vagrant/setup_zfs.sh
		/sbin/modprobe zfs
		zpool create zpool1 mirror /dev/sdb /dev/sdc
		wget -O /tmp/linux-5.19.4.tar.xz  https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.19.4.tar.xz
		wget -O /tmp/War_and_Peace.txt http://www.gutenberg.org/ebooks/2600.txt.utf-8
		wget -O /tmp/zfs_task1.tar.gz 'https://drive.google.com/uc?export=download&id=1KRBNW33QWqbvbVHa3hLJivOAt60yukkg'
		wget -O /tmp/otus_task2.file 'https://drive.google.com/uc?export=download&id=1gH8gCL9y7Nd5Ti3IRmplZPF1XjzxeRAG'
	SHELL
  end
end
