# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'open3'
require 'fileutils'

Vagrant.configure("2") do |config|

config.vm.define "server-rpm" do |server|
  config.vm.box = 'centos/8.4'
  config.vm.box_url = 'http://cloud.centos.org/centos/8/vagrant/x86_64/images/CentOS-8-Vagrant-8.4.2105-20210603.0.x86_64.vagrant-virtualbox.box'

  server.vm.host_name = 'server'
  server.vm.network :private_network, ip: "10.0.0.50"

  server.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  server.vm.provision "shell", inline: <<-SHELL
		cd /etc/yum.repos.d/
		sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
		sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
		touch /etc/profile.d/histtimeformat.sh
		echo "export HISTTIMEFORMAT='[ %d/%m/%y %T ]'">> /etc/profile.d/histtimeformat.sh
		yum install -y mc wget  lsof epel-release && yum install -y libmodulemd && yum groupinstall "Development Tools" -y && yum install -y  pcre pcre-devel  openssl openssl-devel libxslt libxslt-devel gd gd-devel perl perl-devel geoip geoip-devel gperftools  gperftools-devel rpmdevtools rpmlint createrepo
		wget -O /tmp/nginx-1.23.1.tar.gz https://nginx.org/download/nginx-1.23.1.tar.gz
		wget -O /tmp/nginx-1.23.1-1.el8.ngx.src.rpm  https://nginx.org/packages/mainline/centos/8/SRPMS/nginx-1.23.1-1.el8.ngx.src.rpm
		tar -xf /tmp/nginx-1.23.1.tar.gz -C /tmp/
	SHELL
  end


  config.vm.define "client-rpm" do |client|
    client.vm.box = 'centos/8.4'
    client.vm.host_name = 'client'
    client.vm.network :private_network, ip: "10.0.0.51"
    client.vm.provider :virtualbox do |vb|
      vb.memory = "1024"
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    end
	
	client.vm.provision "shell", inline: <<-SHELL
		cd /etc/yum.repos.d/
		sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
		sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
		touch /etc/profile.d/histtimeformat.sh
		echo "export HISTTIMEFORMAT='[ %d/%m/%y %T ]'">> /etc/profile.d/histtimeformat.sh
		yum install -y mc wget  lsof  epel-release && yum install -y libmodulemd
	SHELL
  end

end
