# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'open3'
require 'fileutils'

Vagrant.configure("2") do |config|

config.vm.define "server" do |server|
  config.vm.box = 'centos/8.4'
  config.vm.box_url = 'http://cloud.centos.org/centos/8/vagrant/x86_64/images/CentOS-8-Vagrant-8.4.2105-20210603.0.x86_64.vagrant-virtualbox.box'

  server.vm.host_name = 'server'
  server.vm.network :private_network, ip: "10.0.0.40"

  server.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  server.vm.provision "shell", inline: <<-SHELL
		cd /etc/yum.repos.d/
		sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
		sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
		touch /etc/profile.d/histtimeformat.sh
		echo "export HISTTIMEFORMAT='[ %d/%m/%y %T ]'">> /etc/profile.d/histtimeformat.sh
		yum install -y mc wget  lsof nfs-utils
		bash /vagrant/init.sh
		systemctl enable firewalld.service
		systemctl enable nfs-server
		systemctl start firewalld.service
		systemctl start nfs-server
		firewall-cmd --permanent --add-service=nfs
		firewall-cmd --permanent --add-service=rpc-bind
		firewall-cmd --permanent --add-service=mountd
		firewall-cmd --permanent --add-port=2049/udp
		firewall-cmd --reload
		mkdir  -p /share
		mkdir  -p /share/upload
		chmod -R  777 /share/*
		sed -i 's/# vers3=y/vers3=y/g' /etc/nfs.conf
		sed -i 's/# tcp=y/# tcp=y\\nudp=y/g' /etc/nfs.conf
		echo "/share 10.0.0.0/24(rw,sync,no_root_squash,no_all_squash)" >> /etc/exports
		exportfs -arv
		systemctl restart nfs-server.service
	SHELL
  end


  config.vm.define "client" do |client|
    client.vm.box = 'centos/8.4'
    client.vm.host_name = 'client'
    client.vm.network :private_network, ip: "10.0.0.41"
    client.vm.provider :virtualbox do |vb|
      vb.memory = "1024"
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    end
	
	client.vm.provision "shell", inline: <<-SHELL
		cd /etc/yum.repos.d/
		sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
		sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
		touch /etc/profile.d/histtimeformat.sh
		echo "export HISTTIMEFORMAT='[ %d/%m/%y %T ]'">> /etc/profile.d/histtimeformat.sh
		yum install -y mc wget  lsof nfs-utils nfs4-acl-tools 
		bash /vagrant/init.sh
		mkdir -p /mnt/share
		#mount -t nfs 10.0.0.40:/share/ /mnt/share/
		echo "10.0.0.40:/share/ /mnt/share/ nfs vers=3,proto=udp,ro,sync,hard,intr 0 0" >> /etc/fstab
		echo "10.0.0.40:/share/upload /mnt/share/upload nfs vers=3,proto=udp,rw,sync,hard,intr 0 0" >> /etc/fstab
		mount -a
	SHELL
  end

end
